import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1763968738789 implements MigrationInterface {
    name = 'InitSchema1763968738789'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "department" ("dept_id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "permissions" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_471da4b90e96c1ebe0af221e07b" UNIQUE ("name"), CONSTRAINT "PK_dd43bcc4c4d26f5efeb47d19e79" PRIMARY KEY ("dept_id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_category" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_697de7a94023ebb8a8e62c14f0a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("item_id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "info" text, "quantity" double precision NOT NULL DEFAULT '0', "quantity_unit" character varying(64), "enabled" boolean NOT NULL DEFAULT true, "image" text, "code" character varying, "price" double precision, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category_id" integer, CONSTRAINT "PK_c5ace48ce9474257882dfe16d3c" PRIMARY KEY ("item_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_stock_out_status_enum" AS ENUM('PENDING', 'APPROVED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "inventory_stock_out" ("id" SERIAL NOT NULL, "quantity" double precision NOT NULL, "purpose" character varying(255), "status" "public"."inventory_stock_out_status_enum" NOT NULL DEFAULT 'PENDING', "occurred_at" TIMESTAMP, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "item_id" integer, "requested_by" integer, "approved_by" integer, "repair_id" integer, CONSTRAINT "PK_1405a3373a9eb75df9ad118d54b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "repair" ("repair_id" SERIAL NOT NULL, "location_issue" character varying, "recommendation" character varying, "note" character varying, "status_request" character varying NOT NULL DEFAULT 'pending', "inspection_materials" jsonb, "inspection_created_at" TIMESTAMP, "inspection_approved_at" TIMESTAMP, "inspection_duration_minutes" integer, "damage_description" jsonb, "damage_cause" jsonb, "repair_solution" jsonb, "inspection_notes" text, "inspection_other_opinions" text, "status_inspection" character varying NOT NULL DEFAULT 'inspection_pending', "acceptance_result" text, "acceptance_note" text, "acceptance_created_at" TIMESTAMP, "acceptance_approved_at" TIMESTAMP, "acceptance_duration_minutes" integer, "failure_cause" text, "recovered_materials" jsonb, "materials_to_scrap" jsonb, "acceptance_other_opinions" text, "status_acceptance" character varying NOT NULL DEFAULT 'acceptance_pending', "canceled" boolean NOT NULL DEFAULT false, "canceled_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "device_id" integer, "created_by" integer, "created_department_id" integer, "approved_by_manager_request" integer, "approved_by_admin_request" integer, "approved_by_manager_inspection" integer, "approved_by_admin_inspection" integer, "approved_by_manager_acceptance" integer, "approved_by_admin_acceptance" integer, CONSTRAINT "PK_b1ef4cc55232abb7481eefbc931" PRIMARY KEY ("repair_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."device_status_enum" AS ENUM('moi', 'dang_su_dung', 'thanh_ly', 'huy_bo')`);
        await queryRunner.query(`CREATE TABLE "device" ("device_id" SERIAL NOT NULL, "name" character varying, "brand" character varying, "status" "public"."device_status_enum" NOT NULL DEFAULT 'moi', "note" character varying, "usage_purpose" character varying, "operating_scope" character varying, "country_of_origin" character varying, "manufacture_year" integer DEFAULT '0', "usage_start_year" integer DEFAULT '0', "serial_number" character varying, "technical_code_address" character varying, "location_coordinates" character varying, "daily_operation_time" character varying, "relocation_origin" character varying, "relocation_year" integer DEFAULT '0', "fixed_asset_code" character varying, "using_department" character varying, "weight" character varying, "width" character varying, "height" character varying, "power_source" character varying, "power_consumption" character varying, "other_specifications" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17d554d4f6b44ff0e200ee4b920" PRIMARY KEY ("device_id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("user_id" SERIAL NOT NULL, "name" character varying, "email" character varying, "position" character varying, "password" character varying, "status" character varying, "role" character varying, "citizen_identification_card" character varying, "avatar" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "reset_token" character varying, "reset_token_expiry" TIMESTAMP, "dept_id" integer, CONSTRAINT "PK_758b8ce7c18b9d347461b30228d" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "message" character varying NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userUserId" integer, "departmentDeptId" integer, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_status_enum" AS ENUM('active', 'inactive', 'canceled')`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_level_enum" AS ENUM('3_month', '6_month', '9_month', '12_month')`);
        await queryRunner.query(`CREATE TABLE "maintenance" ("maintenance_id" SERIAL NOT NULL, "scheduled_date" TIMESTAMP, "expired_date" TIMESTAMP, "status" "public"."maintenance_status_enum" NOT NULL DEFAULT 'active', "description" text, "level" "public"."maintenance_level_enum" NOT NULL, "last_notified_slot" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "device_id" integer, "user_id" integer, "dept_id" integer, CONSTRAINT "PK_7ba32feeb1b035188d3a2294422" PRIMARY KEY ("maintenance_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."maintenance_tickets_status_enum" AS ENUM('open', 'in_progress', 'done', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "maintenance_tickets" ("ticket_id" SERIAL NOT NULL, "status" "public"."maintenance_tickets_status_enum" NOT NULL DEFAULT 'open', "scheduled_at" TIMESTAMP, "started_at" TIMESTAMP, "completed_at" TIMESTAMP, "description" text, "last_notified_slot" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "maintenance_id" integer, "device_id" integer, "user_id" integer, "dept_id" integer, CONSTRAINT "PK_08f970a6b6b53239c1cc40de724" PRIMARY KEY ("ticket_id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_item_transaction" ("id" SERIAL NOT NULL, "delta" double precision NOT NULL, "purpose" character varying(255), "occurred_at" TIMESTAMP NOT NULL, "note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "item_id" integer, "user_id" integer, CONSTRAINT "PK_27123e0cf1f8344d0f3f475af63" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('INSERT', 'UPDATE', 'DELETE', 'ROLLBACK')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "entity_name" character varying NOT NULL, "entity_id" character varying NOT NULL, "action" "public"."audit_logs_action_enum" NOT NULL, "actor_user_id" integer, "before" json, "after" json, "diff" json, "reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "rolled_back" boolean NOT NULL DEFAULT false, "rolled_back_at" TIMESTAMP, "transactionId" integer, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_459b098e7cbb3701133b1026fc" ON "audit_logs" ("entity_name", "entity_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "audit_transactions" ("id" SERIAL NOT NULL, "actor_user_id" integer, "reason" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c7ad8408559ab09fcb639348b46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "repair_inspection_committee" ("repair_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_e8b8b1cb5f26ed20ea0bae40bb6" PRIMARY KEY ("repair_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9370892a253c05c59919c56598" ON "repair_inspection_committee" ("repair_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dac85604339f401888851d4e5c" ON "repair_inspection_committee" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "repair_acceptance_committee" ("repair_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_3fed24dcfcca28b2f6a6a3c5ff0" PRIMARY KEY ("repair_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e01e67041f581cce3170a175d3" ON "repair_acceptance_committee" ("repair_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f505c02be016e31a37b844d966" ON "repair_acceptance_committee" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user_devices_device" ("userUserId" integer NOT NULL, "deviceDeviceId" integer NOT NULL, CONSTRAINT "PK_38bdf8158fcfd6ac094b77b6a41" PRIMARY KEY ("userUserId", "deviceDeviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90635435de8a2e8c0b4066befe" ON "user_devices_device" ("userUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f8212200224680d7c769d26b40" ON "user_devices_device" ("deviceDeviceId") `);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_f60710f43431363ad5334bda8db" FOREIGN KEY ("category_id") REFERENCES "inventory_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" ADD CONSTRAINT "FK_131d3861bfc031c2d44fbb64d69" FOREIGN KEY ("item_id") REFERENCES "inventory_item"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" ADD CONSTRAINT "FK_f177f1ea2f542e6c732a70eade2" FOREIGN KEY ("requested_by") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" ADD CONSTRAINT "FK_409f112ff803f89148ec0942af6" FOREIGN KEY ("approved_by") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" ADD CONSTRAINT "FK_7b8fe3bf59342afb38d937b1464" FOREIGN KEY ("repair_id") REFERENCES "repair"("repair_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_022f97beec52b01a6370bdb94b1" FOREIGN KEY ("device_id") REFERENCES "device"("device_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_5d7b88095ed3903baa1122a63b7" FOREIGN KEY ("created_by") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_be98b2a10d3b54bcf9d79b7999a" FOREIGN KEY ("created_department_id") REFERENCES "department"("dept_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_cac257883592b91c3a1742986ec" FOREIGN KEY ("approved_by_manager_request") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_567584a7034839d5390cbe60e9a" FOREIGN KEY ("approved_by_admin_request") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_5c10c193e35d782157524447502" FOREIGN KEY ("approved_by_manager_inspection") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_98a2717d3edbdfd3e8958b581ed" FOREIGN KEY ("approved_by_admin_inspection") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_b681bcbfc48dc1d4f474bdb843a" FOREIGN KEY ("approved_by_manager_acceptance") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair" ADD CONSTRAINT "FK_ddaac8ddac70cc840ced6169413" FOREIGN KEY ("approved_by_admin_acceptance") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c330c4acd2740fac489be6d2889" FOREIGN KEY ("dept_id") REFERENCES "department"("dept_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_03879f1bfdb3efdf24e732d8c73" FOREIGN KEY ("userUserId") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_82e5b2c789821e44cf9b5739801" FOREIGN KEY ("departmentDeptId") REFERENCES "department"("dept_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance" ADD CONSTRAINT "FK_6a18e0a94ac9cc22445d031d1cb" FOREIGN KEY ("device_id") REFERENCES "device"("device_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance" ADD CONSTRAINT "FK_5b2f691377790611b2f19aa11a6" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance" ADD CONSTRAINT "FK_a7319b2d3c605141953bc9b6567" FOREIGN KEY ("dept_id") REFERENCES "department"("dept_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "FK_3f58d7a2db471feebecfe5e30de" FOREIGN KEY ("maintenance_id") REFERENCES "maintenance"("maintenance_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "FK_75d575cacb43a21c893d69644cc" FOREIGN KEY ("device_id") REFERENCES "device"("device_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "FK_be5c76d8d7aba805bba22a13f3e" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" ADD CONSTRAINT "FK_0179c3847842455bd4061001b7e" FOREIGN KEY ("dept_id") REFERENCES "department"("dept_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item_transaction" ADD CONSTRAINT "FK_b9165a941c0e6580689ade63f25" FOREIGN KEY ("item_id") REFERENCES "inventory_item"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item_transaction" ADD CONSTRAINT "FK_d0c78234be99f36f5f938c36a62" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_be80872dfaac5478a829d1c764a" FOREIGN KEY ("transactionId") REFERENCES "audit_transactions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "repair_inspection_committee" ADD CONSTRAINT "FK_9370892a253c05c59919c565981" FOREIGN KEY ("repair_id") REFERENCES "repair"("repair_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "repair_inspection_committee" ADD CONSTRAINT "FK_dac85604339f401888851d4e5c0" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "repair_acceptance_committee" ADD CONSTRAINT "FK_e01e67041f581cce3170a175d3c" FOREIGN KEY ("repair_id") REFERENCES "repair"("repair_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "repair_acceptance_committee" ADD CONSTRAINT "FK_f505c02be016e31a37b844d966d" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_devices_device" ADD CONSTRAINT "FK_90635435de8a2e8c0b4066befe2" FOREIGN KEY ("userUserId") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_devices_device" ADD CONSTRAINT "FK_f8212200224680d7c769d26b400" FOREIGN KEY ("deviceDeviceId") REFERENCES "device"("device_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_devices_device" DROP CONSTRAINT "FK_f8212200224680d7c769d26b400"`);
        await queryRunner.query(`ALTER TABLE "user_devices_device" DROP CONSTRAINT "FK_90635435de8a2e8c0b4066befe2"`);
        await queryRunner.query(`ALTER TABLE "repair_acceptance_committee" DROP CONSTRAINT "FK_f505c02be016e31a37b844d966d"`);
        await queryRunner.query(`ALTER TABLE "repair_acceptance_committee" DROP CONSTRAINT "FK_e01e67041f581cce3170a175d3c"`);
        await queryRunner.query(`ALTER TABLE "repair_inspection_committee" DROP CONSTRAINT "FK_dac85604339f401888851d4e5c0"`);
        await queryRunner.query(`ALTER TABLE "repair_inspection_committee" DROP CONSTRAINT "FK_9370892a253c05c59919c565981"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_be80872dfaac5478a829d1c764a"`);
        await queryRunner.query(`ALTER TABLE "inventory_item_transaction" DROP CONSTRAINT "FK_d0c78234be99f36f5f938c36a62"`);
        await queryRunner.query(`ALTER TABLE "inventory_item_transaction" DROP CONSTRAINT "FK_b9165a941c0e6580689ade63f25"`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" DROP CONSTRAINT "FK_0179c3847842455bd4061001b7e"`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" DROP CONSTRAINT "FK_be5c76d8d7aba805bba22a13f3e"`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" DROP CONSTRAINT "FK_75d575cacb43a21c893d69644cc"`);
        await queryRunner.query(`ALTER TABLE "maintenance_tickets" DROP CONSTRAINT "FK_3f58d7a2db471feebecfe5e30de"`);
        await queryRunner.query(`ALTER TABLE "maintenance" DROP CONSTRAINT "FK_a7319b2d3c605141953bc9b6567"`);
        await queryRunner.query(`ALTER TABLE "maintenance" DROP CONSTRAINT "FK_5b2f691377790611b2f19aa11a6"`);
        await queryRunner.query(`ALTER TABLE "maintenance" DROP CONSTRAINT "FK_6a18e0a94ac9cc22445d031d1cb"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_82e5b2c789821e44cf9b5739801"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_03879f1bfdb3efdf24e732d8c73"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c330c4acd2740fac489be6d2889"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_ddaac8ddac70cc840ced6169413"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_b681bcbfc48dc1d4f474bdb843a"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_98a2717d3edbdfd3e8958b581ed"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_5c10c193e35d782157524447502"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_567584a7034839d5390cbe60e9a"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_cac257883592b91c3a1742986ec"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_be98b2a10d3b54bcf9d79b7999a"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_5d7b88095ed3903baa1122a63b7"`);
        await queryRunner.query(`ALTER TABLE "repair" DROP CONSTRAINT "FK_022f97beec52b01a6370bdb94b1"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" DROP CONSTRAINT "FK_7b8fe3bf59342afb38d937b1464"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" DROP CONSTRAINT "FK_409f112ff803f89148ec0942af6"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" DROP CONSTRAINT "FK_f177f1ea2f542e6c732a70eade2"`);
        await queryRunner.query(`ALTER TABLE "inventory_stock_out" DROP CONSTRAINT "FK_131d3861bfc031c2d44fbb64d69"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_f60710f43431363ad5334bda8db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8212200224680d7c769d26b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90635435de8a2e8c0b4066befe"`);
        await queryRunner.query(`DROP TABLE "user_devices_device"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f505c02be016e31a37b844d966"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e01e67041f581cce3170a175d3"`);
        await queryRunner.query(`DROP TABLE "repair_acceptance_committee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dac85604339f401888851d4e5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9370892a253c05c59919c56598"`);
        await queryRunner.query(`DROP TABLE "repair_inspection_committee"`);
        await queryRunner.query(`DROP TABLE "audit_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_459b098e7cbb3701133b1026fc"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_item_transaction"`);
        await queryRunner.query(`DROP TABLE "maintenance_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_tickets_status_enum"`);
        await queryRunner.query(`DROP TABLE "maintenance"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."maintenance_status_enum"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "device"`);
        await queryRunner.query(`DROP TYPE "public"."device_status_enum"`);
        await queryRunner.query(`DROP TABLE "repair"`);
        await queryRunner.query(`DROP TABLE "inventory_stock_out"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_stock_out_status_enum"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP TABLE "inventory_category"`);
        await queryRunner.query(`DROP TABLE "department"`);
    }

}
